fox_categories = {
    'world': 'World',
    'weather': 'World',
    'us': 'US News',
    'politics': 'Politics',
    'entertainment': 'Entertainment',
    'tech': 'Science/Tech',
    'science': 'Science/Tech',
    'lifestyle': 'Lifestyle',
    'travel': 'Lifestyle',
    'health': 'Lifestyle',
    'style-and-beauty': 'Lifestyle',
    'great-outdoors': 'Lifestyle',
    'food-drink': 'Lifestyle',
    'sports': 'Sports',
    'auto': 'Auto',
    'business': 'Business',  # missing, foxbusiness
}

cnn_categories = {
    'sports': 'Sports',  # missing, cnn has bleacher report
    'travel': 'Lifestyle',  # different index
    'health': 'Lifestyle',
    'style': 'Lifestyle',  # different index
    'politics': 'Politics',
    'us': 'US News',
    'world': 'World',
    'europe': 'World',
    'africa': 'World',
    'americas': 'World',
    'asia': 'World',
    'australia': 'World',
    'china': 'World',
    'india': 'World',
    'middleeast': 'World',
    'uk': 'World',
    'energy': 'World',
    'opinions': 'World',
    'weather': 'World',
    'business': 'Business',
    'economy': 'Business',
    'investing': 'Business',
    'media': 'World',
    'homes': 'Business',
    'success': 'Business',
    'perspectives': 'Business',
    'tech': 'Science/Tech',
    'entertainment': 'Entertainment',
    'cars': 'Auto',
}

categories = {
    'africa': 'World',
    'americas': 'World',
    'asia': 'World',
    'australia': 'World',
    'auto': 'Auto',
    'business': 'Business',
    'cars': 'Auto',
    'china': 'World',
    'economy': 'Business',
    'energy': 'World',
    'entertainment': 'Entertainment',
    'europe': 'World',
    'food-drink': 'Lifestyle',
    'great-outdoors': 'Lifestyle',
    'health': 'Lifestyle',
    'homes': 'Business',
    'india': 'World',
    'investing': 'Business',
    'lifestyle': 'Lifestyle',
    'media': 'World',
    'middleeast': 'World',
    'opinions': 'World',
    'perspectives': 'Business',
    'politics': 'Politics',
    'science': 'Science/Tech',
    'sports': 'Sports',
    'style': 'Lifestyle',
    'style-and-beauty': 'Lifestyle',
    'success': 'Business',
    'tech': 'Science/Tech',
    'travel': 'Lifestyle',
    'uk': 'World',
    'us': 'US News',
    'weather': 'World',
    'world': 'World',
    'russia': 'World',
    'ukraine': 'World',
    'war': 'Politics',
    'fight': 'Politics'
 }

# total = {**cnn_categories, **fox_categories}
